---
book_repo: pivotal-cf/docs-book-telmetry
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

elastic_search: true

public_host: docs.pivotal.io

feedback_enabled: true

sections:
- repository:
    name: pivotal-cf/docs-telemetry
    ref: '0.5'
  directory: telemetry/0-5
  subnav_template: telemetry_0_5.erb
  product_info:
    use_local_header: true
    latest_stable_version: '0.5'
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Telemetry Collector
    search_placeholder: Search Telemetry Collector 0.5
    url_prefix: telemetry/0-5
    local_product_version: 0.5
    local_header_links: []
    local_header_version_list:
      
